### ISSUE TITLE
Containerize StormClustering python service

### ISSUE THREAD

**Issue by pmpande** [airavata-courses/TeamFlash#33]

**Comment by akmehra** [comment]
Hey, we are facing a new issue with the disk space on the instance. 
-The initial error came when we had setup a couple of microservices as containers and were updating them for testing. All deployments started failing because of low disk space on our instance. 
-This was surprising to me because there was like 4.5 gig empty when I started deploying containers. On checking the sizes of containers I could see that each container was of around 400mb (thus having a max storage of 2 GB) which again doesn't explain why the space ran down to zero. 
-After trying a couple of things, I thought of restarting the instance and giving it a fresh start. I deleted all the containers present on my instance and got like almost 4.5 gig back. I started deploying each container one by one and to my surprise each time I re-deploy a container for a microservice, I lose around 250/300MB. 
- I tried finding why this issue is coming up but the nearest I could reach was a difference of AUF's and docker devicemapper.

Could you please help us with this and suggest us why this may be happening with our application? 
 @marpierc @gouravshenoy
